"""B 站 yt-dlp 请求鉴权辅助。"""

from __future__ import annotations

import os
import tempfile
from contextlib import contextmanager
from typing import Any, Dict, Iterator, Optional


def sanitize_sessdata(value: str | None) -> str:
    return (value or "").strip().replace("\r", "").replace("\n", "")


def apply_bilibili_ydl_headers(ydl_opts: Dict[str, Any]) -> Dict[str, Any]:
    """注入 B 站请求所需的 Referer/Origin，降低 playurl 412 风险。"""
    headers = dict(ydl_opts.get("http_headers") or {})
    headers.setdefault("Referer", "https://www.bilibili.com/")
    headers.setdefault("Origin", "https://www.bilibili.com")
    headers.pop("Cookie", None)
    ydl_opts["http_headers"] = headers
    return ydl_opts


def write_bilibili_cookiefile(sessdata: str, directory: str | None = None) -> str:
    """写入 Netscape cookie 文件，返回路径。调用方负责删除。"""
    cookie_value = sanitize_sessdata(sessdata)
    if not cookie_value:
        raise ValueError("SESSDATA 为空，无法写入 cookie 文件")

    fd, path = tempfile.mkstemp(prefix="bili_cookies_", suffix=".txt", dir=directory)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write("# Netscape HTTP Cookie File\n")
            handle.write("# This file was generated by ShengWen for yt-dlp.\n")
            handle.write(".bilibili.com\tTRUE\t/\tFALSE\t0\tSESSDATA\t" + cookie_value + "\n")
    except Exception:
        try:
            os.unlink(path)
        except OSError:
            pass
        raise
    return path


@contextmanager
def bilibili_ydl_auth_context(
    ydl_opts: Dict[str, Any],
    sessdata: str | None = "",
    cookie_dir: str | None = None,
) -> Iterator[Dict[str, Any]]:
    """
    为 yt-dlp 注入 B 站鉴权（headers + 可选 cookiefile）。

    使用 cookie 文件而不是 Cookie 请求头，避免 yt-dlp 弃用警告。
    """
    apply_bilibili_ydl_headers(ydl_opts)
    cookie_path: Optional[str] = None
    cookie_value = sanitize_sessdata(sessdata)
    if cookie_value:
        cookie_path = write_bilibili_cookiefile(cookie_value, directory=cookie_dir)
        ydl_opts["cookiefile"] = cookie_path
    try:
        yield ydl_opts
    finally:
        if cookie_path:
            ydl_opts.pop("cookiefile", None)
            try:
                os.unlink(cookie_path)
            except OSError:
                pass


# 兼容旧调用：仅设置 headers，不写 Cookie 头、不落盘 cookie 文件。
def apply_bilibili_ydl_auth(ydl_opts: Dict[str, Any], sessdata: str | None = "") -> Dict[str, Any]:
    del sessdata  # cookie 请改用 bilibili_ydl_auth_context
    return apply_bilibili_ydl_headers(ydl_opts)
